profiles:
  case:
    git:
      name: CASE
      email: case@zoobz.io
    github:
      user: case-zbz

  flatline:
    git:
      name: FLATLINE
      email: flatline@zoobz.io
    github:
      user: flatline-zbz

  wintermute:
    git:
      name: WINTERMUTE
      email: wintermute@zoobz.io
    github:
      user: wintermute-zbz
